direction: down

COMMIT: "git commit"
    PRE: "pre-commit hook"
    MSG: "commit-msg hook"
    POST: "post-commit hook"
    PUSH: "git push"
    PREPUSH: "pre-push hook"
    SERVER: "server-side\npre-receive / update"
    COMMIT -> PRE
    PRE -> MSG
    MSG -> POST
    PUSH -> PREPUSH
    PREPUSH -> SERVER
