shape: sequence_diagram

Host: Host
Switch: Switch
DHCP: "DHCP Server"
GW: "Default Gateway"
NTP: "NTP Server"
Host -> Switch: "DHCP Discover (broadcast)"
Switch -> DHCP: "Forward broadcast"
DHCP -> Host: "DHCP Offer (IP, mask, GW, DNS)"
Host -> DHCP: "DHCP Request (accept offer)"
DHCP -> Host: "DHCP ACK (lease time)"
Host -> Switch: "ARP Who-has GW IP?"
GW -> Host: "ARP Reply (MAC address)"
Host -> GW: "ICMP Echo Request (ping)"
GW -> Host: "ICMP Echo Reply"
Host -> NTP: "NTP client query (UDP 123)"
NTP -> Host: "Time sync response"
